services:
  qdrant:
    profiles: ["skip"]

  db:
    ports: !override
      - "5434:5432"

  api:
    environment:
      QDRANT_URL: http://host.docker.internal:6333
    depends_on: !override
      db:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    ports: !override
      - "3001:3000"
