"""SQLAlchemy 테이블 정의 단일 출처.

원래 api/routers/notices.py에 있던 metadata + Table 정의를 이동한 것 (정의 무변경).
alembic/env.py의 autogenerate 기준 metadata이자, 테스트 conftest의 create_all 기준.
라우터·서비스·컬렉터 전부 여기서 import한다 (api.routers.notices의 re-export는 하위 호환용).
"""

from __future__ import annotations

from sqlalchemy import (
    JSON,
    Boolean,
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    Numeric,
    String,
    Table,
    Text,
    UniqueConstraint,
    func,
)

metadata = MetaData()

bid_pipeline = Table(
    "bid_pipeline",
    metadata,
    Column("notice_no", String, primary_key=True),
    Column("title", String),
    Column("source", String),
    Column("raw", JSON),
    Column("category", String),
    Column("fit_score", Integer),
    Column("assignee", String),
    Column("analysis", JSON),
    Column("status", String),
    Column("created_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
    # G2B 수집 컬럼 (db/migrations/0001_collect_columns.sql)
    Column("bid_no", String),
    Column("bid_seq", String),
    Column("bid_type", String),
    Column("org_code", String),
    Column("org_name", String),
    Column("base_price", Numeric(18, 2)),
    Column("open_date", DateTime(timezone=True)),
    Column("close_date", DateTime(timezone=True)),
    Column("collected_at", DateTime(timezone=True)),
    # M3 그레이딩 컬럼 (db/migrations/0002_grade_columns.sql)
    Column("score_spec", Numeric(4, 3)),
    Column("score_qual", Numeric(4, 3)),
    Column("score_price", Numeric(4, 3)),
    Column("score_total", Numeric(4, 3)),
    Column("grade_reason", String),
    Column("risk_note", String),
    Column("top_sku", String),
    Column("top_sku_name", String),
    Column("sku_match_score", Numeric(4, 3)),
    Column("graded_at", DateTime(timezone=True)),
)

notice_spec_items = Table(
    "notice_spec_items",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("notice_no", String, ForeignKey("bid_pipeline.notice_no", ondelete="CASCADE"), nullable=False),
    Column("item_key", String, nullable=False),
    Column("label", String, nullable=False),
    Column("required_value", Text),
    Column("proposed_value", Text),
    Column("unit", String),
    Column("category", String, nullable=False, default="technical"),
    Column("source", String, nullable=False, default="rule"),
    Column("confidence", Numeric(4, 3), nullable=False, default=0),
    Column("evidence", JSON, nullable=False, default=dict),
    Column("status", String, nullable=False, default="candidate"),
    Column("sort_order", Integer, nullable=False, default=0),
    Column("note", Text),
    Column("reviewed_by", String),
    Column("reviewed_at", DateTime(timezone=True)),
    Column("locked_fields", JSON, nullable=False, default=list),
    Column("source_text", Text),
    Column("source_file_name", String),
    Column("source_page", String),
    Column("review_priority", String, nullable=False, default="normal"),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("notice_no", "item_key", name="notice_spec_items_notice_item_unique"),
    CheckConstraint("status IN ('candidate','reviewed','matched','gap','ignored')"),
    CheckConstraint("review_priority IN ('normal','high')"),
    Index("notice_spec_items_notice_idx", "notice_no"),
    Index("notice_spec_items_status_idx", "status"),
)

notice_exports = Table(
    "notice_exports",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("notice_no", String, ForeignKey("bid_pipeline.notice_no", ondelete="CASCADE"), nullable=False),
    Column("kind", String, nullable=False),
    Column("draft_id", String, nullable=False),
    Column("output_path", Text, nullable=False),
    Column("mime", String, nullable=False),
    Column("notes", Text),
    Column("version", String),
    Column("template_version", String),
    Column("validation_status", String, nullable=False, default="passed"),
    Column("validation_errors", JSON, nullable=False, default=list),
    Column("file_size", Integer),
    Column("sha256", String),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("created_by", String),
    Column("deleted_at", DateTime(timezone=True)),
    CheckConstraint("kind IN ('excel','hwp','bid_form_hwp','proposal_hwp')"),
    CheckConstraint("validation_status IN ('passed','warning','failed')"),
    Index("notice_exports_notice_idx", "notice_no"),
    Index("notice_exports_active_idx", "notice_no", "kind", "draft_id", "deleted_at"),
)

hwp_templates = Table(
    "hwp_templates",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("template_key", String, nullable=False),
    Column("kind", String, nullable=False),
    Column("name", String, nullable=False),
    Column("template_path", Text, nullable=False),
    Column("template_version", String),
    Column("active", Boolean, nullable=False, default=True),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("template_key", name="hwp_templates_template_key_unique"),
    CheckConstraint("kind IN ('bid_form','proposal')"),
    Index("hwp_templates_active_idx", "active"),
)

company_profiles = Table(
    "company_profiles",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("profile_key", String, nullable=False),
    Column("company_name", String, nullable=False),
    Column("business_number", String),
    Column("ceo_name", String),
    Column("address", Text),
    Column("profile_metadata", JSON, nullable=False, default=dict),
    Column("active", Boolean, nullable=False, default=True),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("profile_key", name="company_profiles_profile_key_unique"),
    Index("company_profiles_active_idx", "active"),
)

document_field_mappings = Table(
    "document_field_mappings",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("template_id", Integer, ForeignKey("hwp_templates.id", ondelete="CASCADE"), nullable=False),
    Column("hwp_field_name", String, nullable=False),
    Column("context_path", String, nullable=False),
    Column("value_type", String, nullable=False, default="string"),
    Column("required", Boolean, nullable=False, default=False),
    Column("default_value", Text),
    Column("transform", String, nullable=False, default="none"),
    Column("sort_order", Integer, nullable=False, default=0),
    Column("active", Boolean, nullable=False, default=True),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint(
        "template_id",
        "hwp_field_name",
        name="document_field_mappings_template_field_unique",
    ),
    CheckConstraint(
        "transform IN ('none','date_yyyy_mm_dd','number_comma','business_number_dash','strip','truncate_1000')",
        name="document_field_mappings_transform_check",
    ),
    Index("document_field_mappings_template_idx", "template_id", "active", "sort_order"),
)

hwp_generation_jobs = Table(
    "hwp_generation_jobs",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("notice_no", String, ForeignKey("bid_pipeline.notice_no", ondelete="CASCADE"), nullable=False),
    Column("template_id", Integer, ForeignKey("hwp_templates.id", ondelete="SET NULL")),
    Column("export_id", Integer, ForeignKey("notice_exports.id", ondelete="SET NULL")),
    Column("status", String, nullable=False, default="pending"),
    Column("context_json", JSON, nullable=False, default=dict),
    Column("input_values", JSON, nullable=False, default=dict),
    Column("replaced", JSON, nullable=False, default=list),
    Column("missing", JSON, nullable=False, default=list),
    Column("remaining_placeholders", JSON, nullable=False, default=list),
    Column("worker_raw", JSON, nullable=False, default=dict),
    Column("error_detail", Text),
    Column("review_status", String, nullable=False, default="pending"),
    Column("review_note", Text),
    Column("reviewed_by", String),
    Column("reviewed_at", DateTime(timezone=True)),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    CheckConstraint("status IN ('pending','running','completed','failed')"),
    CheckConstraint("review_status IN ('pending','approved','rejected')"),
    Index("hwp_generation_jobs_notice_idx", "notice_no"),
    Index("hwp_generation_jobs_review_idx", "review_status"),
)

notice_errors = Table(
    "notice_errors",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("notice_no", String, ForeignKey("bid_pipeline.notice_no", ondelete="CASCADE"), nullable=False),
    Column("stage", String, nullable=False),
    Column("severity", String, nullable=False, default="error"),
    Column("source", String, nullable=False, default="system"),
    Column("file_name", String),
    Column("detail", Text, nullable=False),
    Column("raw", JSON, nullable=False, default=dict),
    Column("resolved_at", DateTime(timezone=True)),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    CheckConstraint("severity IN ('info','warning','error')"),
    Index("notice_errors_notice_idx", "notice_no"),
    Index("notice_errors_unresolved_idx", "notice_no", "resolved_at"),
)

notice_required_documents = Table(
    "notice_required_documents",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("notice_no", String, ForeignKey("bid_pipeline.notice_no", ondelete="CASCADE"), nullable=False),
    Column("doc_name", Text, nullable=False),
    Column("requirement_type", String, nullable=False, default="required"),
    Column("submit_stage", String, nullable=False, default="bid"),
    Column("source_file", Text),
    Column("evidence_text", Text),
    Column("page_no", Integer),
    Column("deadline", String),
    Column("condition", Text),
    Column("confidence", Numeric(4, 3), nullable=False, default=0),
    Column("checked", Boolean, nullable=False, default=False),
    Column("owner", String),
    Column("note", Text),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("notice_no", "doc_name", "submit_stage", name="notice_required_documents_unique"),
    CheckConstraint(
        "requirement_type IN ('required','conditional','winner_only','contract_stage','reference')"
    ),
    CheckConstraint(
        "submit_stage IN ('bid','proposal','price','post_award','contract','delivery','conditional')"
    ),
    Index("notice_required_documents_notice_idx", "notice_no"),
    Index("notice_required_documents_stage_idx", "notice_no", "submit_stage"),
)

attachment_fetch_jobs = Table(
    "attachment_fetch_jobs",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("notice_no", String, ForeignKey("bid_pipeline.notice_no", ondelete="CASCADE"), nullable=False),
    Column("status", String, nullable=False, default="pending"),
    Column("started_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("finished_at", DateTime(timezone=True)),
    Column("created_by", String),
    CheckConstraint("status IN ('pending','running','completed','completed_with_errors')"),
    Index("attachment_fetch_jobs_notice_idx", "notice_no"),
)

attachment_fetch_files = Table(
    "attachment_fetch_files",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("job_id", Integer, ForeignKey("attachment_fetch_jobs.id", ondelete="CASCADE"), nullable=False),
    Column("notice_no", String, ForeignKey("bid_pipeline.notice_no", ondelete="CASCADE"), nullable=False),
    Column("filename", String, nullable=False),
    Column("url", Text, nullable=False),
    Column("status", String, nullable=False, default="pending"),
    Column("upload_id", String),
    Column("error", Text),
    Column("source_ref", String, nullable=False, default="g2b_attachment"),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    CheckConstraint("status IN ('pending','success','failed','skipped')"),
    Index("attachment_fetch_files_job_idx", "job_id"),
    Index("attachment_fetch_files_notice_idx", "notice_no"),
)
